// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ln47PxeGSoiV8NeEduw-ogQG-1SxoQs',
    appId: '1:986552197393:web:d0f331fb40c51ea5162cb0',
    messagingSenderId: '986552197393',
    projectId: 'sistempakar-14e4f',
    authDomain: 'sistempakar-14e4f.firebaseapp.com',
    storageBucket: 'sistempakar-14e4f.firebasestorage.app',
    measurementId: 'G-R622Y73MJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjF8rfes-xr5qk8JWQtleHD5rYLmG25uU',
    appId: '1:986552197393:android:edac6e5bdb548896162cb0',
    messagingSenderId: '986552197393',
    projectId: 'sistempakar-14e4f',
    storageBucket: 'sistempakar-14e4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMm-_3-f9y-J81wpHBink6T9QUJT7k3k',
    appId: '1:986552197393:ios:2e7331934a1f7483162cb0',
    messagingSenderId: '986552197393',
    projectId: 'sistempakar-14e4f',
    storageBucket: 'sistempakar-14e4f.firebasestorage.app',
    iosBundleId: 'com.example.sistemPakar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMm-_3-f9y-J81wpHBink6T9QUJT7k3k',
    appId: '1:986552197393:ios:2e7331934a1f7483162cb0',
    messagingSenderId: '986552197393',
    projectId: 'sistempakar-14e4f',
    storageBucket: 'sistempakar-14e4f.firebasestorage.app',
    iosBundleId: 'com.example.sistemPakar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Ln47PxeGSoiV8NeEduw-ogQG-1SxoQs',
    appId: '1:986552197393:web:fff057797961108c162cb0',
    messagingSenderId: '986552197393',
    projectId: 'sistempakar-14e4f',
    authDomain: 'sistempakar-14e4f.firebaseapp.com',
    storageBucket: 'sistempakar-14e4f.firebasestorage.app',
    measurementId: 'G-BS0JHQ142V',
  );
}
